# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/aiorbits',
                'doc_host': 'https://jbwhit.github.io',
                'git_url': 'https://github.com/jbwhit/aiorbits',
                'lib_path': 'aiorbits'},
  'syms': {'aiorbits.core': {'aiorbits.core.foo': ('core.html#foo', 'aiorbits/core.py')}}}
